import { BrowserRouter, NavLink, Routes, Route, useNavigate, Link } from 'react-router-dom';
import React, { useState, useEffect, Redirect, Navigate} from "react";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './Signup.css'
/* eslint-disable no-useless-escape */



/* MARKER INSTRUCTIONS / CODE REFERENCES:

1) 
    So this contains To check a password between 6 to 20 characters which contain at least one numeric digit, one uppercase and one lowercase letter
    Sourced regex expression from: https://www.w3resource.com/javascript/form/password-validation.php

2) 
    In order to validate our emails we have used the following regex expression and have got it from the following website:

    regex-expression: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/

    regex-email sourced from: https://www.w3resource.com/javascript/form/email-validation.php#:~:text=To%20get%20a%20valid%20email,%5D%2B).

3) 
    In order to validate our first name and last name to only contain letters we have used the following regex expression and got it from the following web:
    
    regex-expression: /^[a-zA-Z]+$/
    regex-letter only expression sourced from: https://stackoverflow.com/questions/3073176/javascript-regex-only-english-letters-allowed
    


*/


const SignUp = ({onLogin}) => {

    // HTML form notes

    // If the name attribute is omitted, the 
    // value of the input field will not be sent at all.

    // - Setting variables for submit element, first and last name
    // - Validating user data from input fields
    // - Creating logic to store information from form to html local storage
    // - navigate() hook, to allow redirects


    // Callback - Child to parent


    const [firstname, setfirstname] = useState('')
    const [lastname, setlastname] = useState('')
    const [valid, setValid] = useState(null)
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')


    let navigate = useNavigate();


        // Saves input in state variables
    function firstnameinput(event) {
         setfirstname(event.target.value);
    }

    function lastnameinput(event) {
        setlastname(event.target.value)
    }

    function emailinput(event) {
        setEmail(event.target.value)
    }

    function passwordinput(event) {
        setPassword(event.target.value)
    }

    function emailError() {
        console.log("yeh error mate email")
        if ((valid === false) && ((email.match(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/) === null))){
            return (
                <div className='AlertMessage'>Error: Make sure email formatting is correct </div>
            )
        }     
    }

    function nameError(nameType){
        if ((valid === false) && ((nameType.match(/^[a-zA-Z]+$/) === null))){
            return (
                <div className='AlertMessage'>Error: Remove numbers or symbols from name</div>
            )

            }     
    }

    function passwordError(){
        if ((valid === false) && ((password.match(/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{8,15}$/) === null))){
            return (
                <div className='AlertMessage'>Error: Passwords should contain 8 to 15 characters, one uppercase letter, one numeric digit and one special character. </div>
            )

            }
    }
    

    function sucessful(){
        if (valid === true){                
            toast.success('Sign-In Sucessful', {
                toastId: 'success1',
            })
    }
    }




        // Validates input
    function validate() {

        /* eslint-disable no-useless-escape */


        if(email.match(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/) && firstname.match(/^[a-zA-Z]+$/) && lastname.match(/^[a-zA-Z]+$/) 
                        && password.match(/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{8,15}$/))
        {
            setValid(true)
            
            console.log("Login set to true")
            
        }
        else {
            setValid(false)

        }   
    }

    function submit() {
        // console.log(firstname, lastname + '\n Soon to validate')

        validate()        
    }


    function redirect() {

        if (valid) {
            // Submits data to localstorage (if valid)

            localStorage.setItem(email,JSON.stringify({
                firstname:firstname,
                lastname:lastname,
                email:email,
                password:password,
                profile_pic:'/9j/4AAQSkZJRgABAQEBLAEsAAD/4QCHRXhpZgAASUkqAAgAAAACAA4BAgBMAAAAJgAAAJiCAgANAAAAcgAAAAAAAABtYWxlIHByb2ZpbGUgaWNvbiwgaXNvbGF0ZWQsIHdoaXRlIG9uIHRoZSBibHVlIGJhY2tncm91bmQuIEV4Y2x1c2l2ZSBTeW1ib2xzcmFzaGFkYXNodXJvdv/hBYlodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+Cjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iPgoJPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KCQk8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iIHhtbG5zOklwdGM0eG1wQ29yZT0iaHR0cDovL2lwdGMub3JnL3N0ZC9JcHRjNHhtcENvcmUvMS4wL3htbG5zLyIgICB4bWxuczpHZXR0eUltYWdlc0dJRlQ9Imh0dHA6Ly94bXAuZ2V0dHlpbWFnZXMuY29tL2dpZnQvMS4wLyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpwbHVzPSJodHRwOi8vbnMudXNlcGx1cy5vcmcvbGRmL3htcC8xLjAvIiAgeG1sbnM6aXB0Y0V4dD0iaHR0cDovL2lwdGMub3JnL3N0ZC9JcHRjNHhtcEV4dC8yMDA4LTAyLTI5LyIgeG1sbnM6eG1wUmlnaHRzPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgZGM6UmlnaHRzPSJyYXNoYWRhc2h1cm92IiBwaG90b3Nob3A6Q3JlZGl0PSJHZXR0eSBJbWFnZXMvaVN0b2NrcGhvdG8iIEdldHR5SW1hZ2VzR0lGVDpBc3NldElEPSI0NzAxMDA4NDgiIHhtcFJpZ2h0czpXZWJTdGF0ZW1lbnQ9Imh0dHBzOi8vd3d3LmlzdG9ja3Bob3RvLmNvbS9sZWdhbC9saWNlbnNlLWFncmVlbWVudD91dG1fbWVkaXVtPW9yZ2FuaWMmYW1wO3V0bV9zb3VyY2U9Z29vZ2xlJmFtcDt1dG1fY2FtcGFpZ249aXB0Y3VybCIgPgo8ZGM6Y3JlYXRvcj48cmRmOlNlcT48cmRmOmxpPnJhc2hhZGFzaHVyb3Y8L3JkZjpsaT48L3JkZjpTZXE+PC9kYzpjcmVhdG9yPjxkYzpkZXNjcmlwdGlvbj48cmRmOkFsdD48cmRmOmxpIHhtbDpsYW5nPSJ4LWRlZmF1bHQiPm1hbGUgcHJvZmlsZSBpY29uLCBpc29sYXRlZCwgd2hpdGUgb24gdGhlIGJsdWUgYmFja2dyb3VuZC4gRXhjbHVzaXZlIFN5bWJvbHM8L3JkZjpsaT48L3JkZjpBbHQ+PC9kYzpkZXNjcmlwdGlvbj4KPHBsdXM6TGljZW5zb3I+PHJkZjpTZXE+PHJkZjpsaSByZGY6cGFyc2VUeXBlPSdSZXNvdXJjZSc+PHBsdXM6TGljZW5zb3JVUkw+aHR0cHM6Ly93d3cuaXN0b2NrcGhvdG8uY29tL3Bob3RvL2xpY2Vuc2UtZ200NzAxMDA4NDgtP3V0bV9tZWRpdW09b3JnYW5pYyZhbXA7dXRtX3NvdXJjZT1nb29nbGUmYW1wO3V0bV9jYW1wYWlnbj1pcHRjdXJsPC9wbHVzOkxpY2Vuc29yVVJMPjwvcmRmOmxpPjwvcmRmOlNlcT48L3BsdXM6TGljZW5zb3I+CgkJPC9yZGY6RGVzY3JpcHRpb24+Cgk8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJ3Ij8+Cv/tAK5QaG90b3Nob3AgMy4wADhCSU0EBAAAAAAAkhwCUAANcmFzaGFkYXNodXJvdhwCeABMbWFsZSBwcm9maWxlIGljb24sIGlzb2xhdGVkLCB3aGl0ZSBvbiB0aGUgYmx1ZSBiYWNrZ3JvdW5kLiBFeGNsdXNpdmUgU3ltYm9scxwCdAANcmFzaGFkYXNodXJvdhwCbgAYR2V0dHkgSW1hZ2VzL2lTdG9ja3Bob3Rv/9sAQwAKBwcIBwYKCAgICwoKCw4YEA4NDQ4dFRYRGCMfJSQiHyIhJis3LyYpNCkhIjBBMTQ5Oz4+PiUuRElDPEg3PT47/9sAQwEKCwsODQ4cEBAcOygiKDs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7/8IAEQgCZAJkAwERAAIRAQMRAf/EABoAAQACAwEAAAAAAAAAAAAAAAAFBgIDBAH/xAAZAQEAAwEBAAAAAAAAAAAAAAAAAQMEAgX/2gAMAwEAAhADEAAAAc9vnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD06eO90dInCY5++NU8EgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADbHUxRokarskgAc3XETdnjraQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB212WDNszSAAABwWVV/Tj8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN/PVnybskgAAAARttEDoyEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAACw5tnfXaAAAAABWNWHm74AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2RNrx+h6AAAAAARVtEJoygAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd1dtizbAAAAAABy9cVnXhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkqrp7PrAAAAAAGqeans8/1IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkqrp7PrAAAAAAGqeans8/1IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkqrp7PrAAAAAAGqeans8/1IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkqrp7PrAAAAAAGqeans8/1IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsGbXIV3AAAAAADFFb1YuXvgAAAAAAAAAAAAAAAAAAAAAAAAAAAADdz1asm8AAAAAAARttMDoyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC24vQzSAAAAAABC35om7OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ/Nrka7gAAAAAAKvrwc/XIAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6+LLLl2gAAAAADj7rrerCSAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJ7PskqrgAAAAB4VfXg0dcgAAAAAAAAAAAAAAAAAAAAAAAAAAAAADbz1acm7JIAAAAEXbRB6MoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmqNMtToAAAAGCKtswa5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZQtGTfujoAAACEvyxV1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6+LLJl2+gAAHF3VXNWMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADxFwxel6AAAQt+aJuzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbIm14/Q9AAAIu2iD0ZCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOnjuxZtm2OgAAAIu2iE0ZfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAESVV85n1ZJAAAAA4+66/px65gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZQnc+uRruAAAAAAGueYDRl4rKSQAAAAAAAAAAAAAAAAAAAAAAAAAAAR213TufVujoAAAAAAACMtohb82EwAAAAAAAAAAAAAAAAAAAAAAAAAAR1cWTFOnurtAAAAAAAAAGuYibs0XbRjIAAAAAAAAAAAAAAAAAAAAAAAAjs4tl6NPbxYAAAAAAAAAAAMJiKtzxV1GEwAAAAAAAAAAAAAAAAAAAAAAR2cWzNGnr4sAAAAAAAAAAAAAGKIq6iJuz4TAAAAAAAAAAAAAAAAAAAAAyhPZ9chXcAAAAAAAAAAAAAAANc8wOjLw2VAAAAAAAAAAAAAAAAAAAASVV09n1gAAAAAAAAAAAAAAADVPNT2ef6kAAAAAAAAAAAAAAAAAAATFGiYp0gAAAAAAAAAAAAAAAAU/b5wAAAAAAAAAAAAAAAAAAAE7n1SdV4AAAAAAAAAAAAAAAAFV14NPXIAAAAAAAAAAAAAAAAAAAseXZ28WgAAAAAAAAAAAAAAAAVrVi5O6wAAAAAAAAAAAAAAAAAACLRk39HPYAAAAAAAAAAAAAAAAEBoyR1tIAAAAAAAAAAAAAAAAAAHiLhi9H1IAAAAAAAAAAAAAAAAELfmibs4AAAAAAAAAAAAAAAAAAA7OLAAAAAAAAAAAAAAAAABpnnT1yAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/EACYQAAEEAgEDBAMBAAAAAAAAAAMAAQIEFFAwERIzEzFAYCAhI6D/2gAIAQEAAQUC/wA7TdXdqxnWEZYJk9MzKQiQ+jDHMrjpQimZot+JADIi05w+h167meMWhHhsVmKnZ4vvwicxGZotx2wd8d/UH2B5bA/SNvYR7yc16PUe9pt1sc1hu6vvaPm5ieLe0fNzE8W9o+bmJ4t7R83MTxb2tX9JuZ26scDgluw+f4F7wbv2UX7o89+X73lKfcHnPP1DbysX0jc1kvpC31MvePlMX1i74RPSIz9W47pe2H0CkXq3FKTRiSbkJ9AjJ4SGRiw4bpur/Qq5/RnwWT+jD6G/s3t+d/3+hwHIsuC6OU2+hBBIzjHEUeGxU717PvwVHmmZmbjNXiZiDkKW8jF5yBUYfPOESRNVkLdhqzKhigKPwTU4zUoyg+2HXIVCqDH8WcIzYlF2UovB9kOqQiHVGP5MoRmxKKlCQ31wqpCoVcYvmvFpMWiylGUH1TM8pBqRHoZwiSJ6zh1VFv66Ijdw9TQbSdOj6ii38dGZuhtRUbpW0dpulnUAboDR3m/vp3TfptHfb96jLOss6yzrLOss6yzrLOss6yzrLOss6yzrLOss6yzrLOss6yzrLOss6yzrLOss6yzrLOss6yzrLOss6yzrLOss6yzrLOss6yzqZpl/0M//xAAnEQABAwQBBAIDAQEAAAAAAAACAAEDERMxUDASMkBgIUFCUqAgUf/aAAgBAwEBPwH+dtoy/wCKySskrRJxJvr0YRcsIYWbKpT/AEQCWUULtj0OOPqTNTHEcfUsegAPU9EzU5JQq1fQIhoPNIPSW+FqvTnmb4rvoe7nkaovvoc85Y30Oecsb6HPOWN9DnnLG+jDp8Aw6X3gdzeDN271nr4E74bewvUfAN6lvYy6S55C6W38RVanMZdT134l0vXlmKjU9BhL8eN3oifqevoLPR6oS6mrxTH+PocZ9L8Mh9Lemz/XojC5fDcMwu/y3oYA5IRYWo3FJFX5b0EIq/L8pxsSIXHO9ZnfCCJm+X53Znyjjcd2ETkhFhx4RxM+E7O2duMZEhiYfFdmfKKH9U7O2dmMROhjEfJdmfKKH9U7O2deMZEhjEfNdqoof1Ts7Z1bNVBEw50Lsz5Rx9Pzqoc6Mmq2qg+/TYe3SH3PqYuzSS9+pDtbSTd3ps/1qbpq6aumrpq6aumrpq6aumrpq6aumrpq6aumrpq6aumrpq6aumrpq6aumrpq6aumrpq6aumrpq6aumrpq6aumiNyz/Qz/8QAJREAAgEDAwUBAQEBAAAAAAAAAQIAAxETMDFQEiFAQWAyUaAg/9oACAECAQE/Af8AO31rMqzKsyLAwPwxIG8NU+v+wxEWoDv8G79MJvpI9vgWbpGrTa3b4CobnWQ3HPE2F9eke9ueqfnXT9c9V21xvz1XbXG/PVdtcb89V21xvzzvfwFbq5xtj4NL9fG0h752oO/gKLDnXW410W55+otjfWVekc+wuLatNe9/gaq+9PeAWFvgT3hFjbSpr7+DderRReo/G0vfwhIHc6NMgfBswWEk6SVLdj8C1S22qrlYCDtzpNo1S+2uDaK4PNs4EJJ38Jalt4Dfbly4EaoT4oJEFX+wd+TLgQuT5INoKv8AYCDtx7OBGcnzlq/2A324vaNUJ4EEjaI/VxVXbgxvxVX18bV34RduJqfrhKf54lt+Epfn42l74nGsxrMazGsxrMazGsxrMazGsxrMazGsxrMazGsxrMazGsxrMazGsxrMazGsxrMazGsxrMazGsxrMazGsxrMawKBt/oZ/8QAMRAAAQIDBQUIAgMBAAAAAAAAAQACETKhEiEwUFEiMUFgcQMTQGFygZGxUqAgM0KC/9oACAEBAAY/Av12oAR6L+v5X+Plb2fK3A9CtphHI0GBbe0aKAEB/Labfqos2hXkOJuZ9qy0QGFaFz/tQIgRyBZ4cVAXAYneNmFeQI8XX4xHA3jPmt1OO1+hz7oI47+mfO9OO7pnzvTju6Z87047umfO9OO7pn1p0xpjwK1adxzxkfy8D755EcEHDj4BjPfPbPFvgHO4bhnt8rrjjn8jcM/sHe3GLuHDPw/5URid2N7vrkHujw3YZcdwReePIIc3eEHDC7of9ch3yHfg3THdyb2fvyJZaMFrmiNnfyHdc3VWWjCt9nc7TVQO/kC12lzdNVAXDE0dqrLxntloiVaftO+sey4RCiNpv1ncTstUGjwVrs9k0UHCBze4QGpUZnanwsHCIUeyMfIqDhA5n+I81GFo6nxMHCIUeyPsVB7YZfGVupVwidT42DhEKPZGHkVBwgcrDWiJKi7ad9ZDBwiFaF7PrKnHQZG4ajKnnpkkNMpPm7JH+rKW5I7KWenJB6cphkjD1ymeinop6Keinop6Keinop6Keinop6Keinop6Keinop6Keinop6Keinop6Keinop6Keinop6Keinop6Keinop6LbMYfsM//EACsQAAECBAQGAwADAQAAAAAAAAEAESExYZEwQVBRYHGhscHwQIHRIKDx4f/aAAgBAQABPyH+u0DpHsDqXkBUAgbMOZfi/wBB+KRe8zUgbdnCd+BYpO5MgosZ2pI3FsAN/KLhoQKdC0vUeA4qgTPggQAEgMIOWd7yRDLAg8AAIwmPYIZGwYDEhJBjRwA3GM9yyxm1GvRy5jyzx2wm0eR9GvN53/DzjtvZ9o697FcfrfZCWu+xXH632QlrvsVx+t9kJa77FcfrfZCWuxohxGVGOA0ghihEP6Aa4zZM+Cxjza2uOSEwnCDKAOPgcmOfjzrsVTW+svgMtm+ga60Ob6DY48JH1XUteij5xikgByWARuQhpr5A2Um4QBEcEODiMJN2nAJ9LGLlwyIsByVmqIDYcAkqYjhSqzlthRLgI/jgP/KKuD6D1USXJcmZ4DmKRgdN4cCRNjmcghAYDNQ5gnlwHl4T/KDWQ6nCARZzMiEEgCAmDlwA2DOVn/CAgAEgMR6SpCoEByOR10ELNkExMZO2OKAkPb+7nza2zO75meSgDbnM/CeGNnN+J9+tq8eTpkF2jkPisf1k8MXvFOX7R1OPEV57Jr+SK0ftEIWR95p6g656ewEOsfSin2Mfmm4hMiER4CT7+0dLy8ACam+jyaCzPWUeTvZ6UepW5/5odV0IS0mFvkPb6IXW82ktG3PGiMOo6Tzm566Jzmx6aSwaO2iMG3DudIkKBgMtE+rB20gFiDsqC1UFqoLVQWqgtVBaqC1UFqoLVQWqgtVBaqC1UFqoLVQWqgtVBaqC1UFqoLVQWqgtVBaqC1UFqoLVQWqgtVBaqC1UFqoLVQWqgtVBahQGaCDf2Gf/2gAMAwEAAgADAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAztGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCwABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2AAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAB2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAABKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABuAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAABKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0AAAAAAAcQAAAAAAAAAAAAAAAAAAAAAAAAAAAHkAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAA2AAAAAAAAAAI2AAAAAAAAAAAAAAAAAAAAAAAAHcAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAA7QAAAAAAAAAAAAAGkAAAAAAAAAAAAAAAAAAAAA2AAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAABeAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA6AAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAOwAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAABCAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//xAAoEQABAwQBBAEEAwAAAAAAAAABABFhITAxUGBAQVFxgSCgofCRscH/2gAIAQMBAT8Q+3aAJLCqLT1/vwpx+/CI+zrKcGFmBVKpAAYD6sIVYrH54GQ3OEAGtB1ChRBJjngBVgAwuULkcAqRybzgBjfMflffHw3wP6i+wo32f1fy+kN7n9X8vpDe5/V/L6Q3uf1fy+kN62c5N8hwxR4t4yt56Fv8945FQgACOgqfJvaJ46B+O9zmDfxuTjf19kXnfs7b8wUBBDi5ROT/AFwF0O7YtgAkopC4CQAZCAALThZ88Dy2DZwWTwQ4QsZfL/OCGLIFHY4GVpjzbAA81EEFjwA/g+EAAGFwDPlEG3oiwVXeQ3xrAqoKjd1I0CAMHRVSk/hHWBtvgAwVayelGsDooqXwiDA2zqJoFVGc9SAYHQckjrA2vrmAqwBXrQAxCGakirA2rITDKqFR0I1gR6VRqhrMaNxCGpChaQhi2pFiM6QGBOpBg0gMWpBgQNINBjUFAMG0gVL3qBSqkUikUikUikUikUikUikUikUikUikUikUikUikUikUikUikUikUikUiBMX3DP/8QAJhEAAQMEAQQCAwEAAAAAAAAAAQARYSEwMVBgQEFRcYGgIKHB8P/aAAgBAgEBPxD67RIFSiLuvYvZ/vlAywR4MNdDPBEklz+WPKolHAwUDKITm0Wk4QIIccAA4iSS5uOnYPAKL2F5nPffPF8wXlvja+Jg32G/iR3uG/iR3uG/iR3uG/iR3r1hi+CxdDCd4+l46F28M9CiGLHoKR3pp/noGkb3F5F/1e/pDBvUjfuyEEFjcec7cBYLbYBJghiDgIAGKO8tNB/xwNlTNnOYHBBlGxj8P7wQLZDhB78DGVyjrm1AFmo4AKjNEklzc9Qhr70AHKNTQL5TcKmmh3dFFSjr9EPRUEAHLb5vKoeB0pBwUI0FEAcbOfKp+B1JCcFdoUActfR8lZPHWgkFwiYUAOWrJAOVSRQaEg5INBzqipGjNgKOpPDSO9dSVPrSE4+tSTnpCcdSbn70hftqAiXL6Q6BqYVCoVCoVCoVCoVCoVCoVCoVCoVCoVCoVCoVCoVCoVCoVCoVCoVCoVD9hqX/xAAsEAEAAQEGBgICAgMBAAAAAAABEQAhMUFhwfAwUFFxgaFgkUCx0eEQoPEg/9oACAEBAAE/EP8AXaz0qF9FFimx9Is+qClymi/wNl/QP8Knk5fYnkkoAkR+C3alwXfdL6IPFQ8Fr5fFCz64QPB/6lpN/wB0v80YqdsyAfrwhyrFLkYRw+BTRVgb101Ow5bwCzhQQgsw5P5X085WLD8AcRCw7Jbj+qP/AAAuDiA17wMG87l55KGSTn1xQx1C3TA+re68YIKsMwG88M+I59Y2wEGy6aAAAgLjjRovRsxPtz4FsC72anHNHEPew9lF3Pdhk4+z9VXHbnuwycfZ+qrjtz3YZOPs/VVx257sMnH2fqq47c87CuAY06sSANhf3PV+s+MV0uCYkaAqlrX2XrM988ZjT7M2e4/BVnWvNh0nng8oInRGSlsk/aST8CULcD656WmSm/bK1e08fgTYkZS4s72vnnpIiEi2LE7NnZeOKo5AG0W/wLe8daAAFxz1JIaZpMQLfgvi7668VEAEqsAVIBjbMDq3/wDOfy4o4DFvNe4UVwYFyNzxLOYrvk+7u0/AbgTWccZ4fTlwwgMIwCpExvjtH18BtxDGjklnmmPsbcSxHtwhCU4hi3nhe+OnwNUmqWS2fQfvLsUMknAIy3KCLCL12k++9KhCFRlVvX4H6zXoHwyu3GS0ueq0IDoRwI5V6UbwYxFCJIyfApHa0OWdup/VEGK1cTquLwjERbdr1yfTj1poKwKFZnP1AlYKxMBcd7o99qNuMAgDI4k6WKCW9nqUt6CLR6jz27wFgZrgZtNqDb1WXVzfXHbmrYcHqODVkN2xLLJ0zPVDJJzlQJWCoBItis8mr7qJMt5avVcfwlErtY/9Xb6p/wBOMR1G5O3NlAlYKjpllCZF7+s6BNC0CxfQe3P8VW+YC7McHMrrQEkPj+X3SQEwYnt1MzmShexUXPsK12vfcU2EW2+RyLj95/kpkzqvOTTp7mKeLx5nvUwnuhZ2Nz45coErBVtAWw2jK8+YKh4//SYHj82+A5KGpCa6qrs3nmfFZN+L8xuTtytwCoDGrNatFLbJq+uQoHjDA9RvHMq2EGFezqZ7eU2LfwjkazmfZDTkvU5ShgvoReSFavT6scpR/EHYBo8kR/8AtM68ptAQ+049RyRkxZG+p+x5Q2DUnkJKZwnklgNnnJ/RygKRapBQ3YIHjkkBy9D9jXlCAXoSybStg6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSts6VtnSivhWBg+D/YZ/9k='
            }))

            onLogin(email)

            navigate('/Profile')
        }
        else {
            localStorage.setItem("Login_Status", "false")
        }
    }


    return (


        <div className="signup-text">
            
            <h1 className = "siginup-Title">Sign-Up Form</h1>

            <h4> Already have an account with LAN? <Link to = '/LoginPage'>Log in here</Link></h4>
            

            <div className="signup-form">

                <form className = "signup-box">
                    <label htmlFor="email">Email Address: </label>
                    <input type='text' id="email-text" onChange={emailinput} required placeholder='John82@test.com.au'></input>
                    {emailError()}
                    


                </form>

                <form className = "signup-box">
                    <label htmlFor="first-name">First Name: </label>
                    <input type='text' id="first-name-text" onChange={firstnameinput} required placeholder='John'></input>
                    {nameError(firstname)}

                </form>
                
                <form className = "signup-box">
                    <label htmlFor="last-name">Last Name: </label>
                    <input type='text' id="last-name-text" onChange={lastnameinput} required placeholder='Patel'></input>
                    {nameError(lastname)}

                </form>

                <form className = "signup-box">
                    <label htmlFor="password">Password: </label>
                    <input type='password' id="password-text" onChange={passwordinput} required placeholder='Enter a strong password'></input>
                    {passwordError()}
                </form>
                
                <button type="submit" onClick ={(e) => submit(e)} className="submit-button">Sign up</button>



                {sucessful()} 

                {redirect()}
 

                </div>
            
        </div>



      

    )
}

export default SignUp;